scss_files: 'app/assets/stylesheets/**'
exclude:
  - 'app/assets/stylesheets/application.css'
  - 'app/assets/stylesheets/sellers/application.css'
  - 'app/assets/stylesheets/sellers/gentelella.min.css'
  - 'app/assets/stylesheets/login_page.scss'
  - 'vendor/assets/**'
  - 'app/assets/stylesheets/sellers/custom.scss'
  - 'app/assets/stylesheets/sellers/product.scss'
  - 'app/assets/stylesheets/material_kit.css'
  - 'app/assets/stylesheets/mk-custom.min.css'
linters:
  Comment:
    exclude:
      - 'app/assets/stylesheets/login_page.scss'
